[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["mg-chao <chao@mgchao.top>"]
repository = "https://github.com/mg-chao/snow-shot"
edition = "2024"
rust-version = "1.85.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2.0.6", features = [] }

[dependencies]
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
tauri = { version = "^2.3", features = [
    "macos-private-api",
    "tray-icon",
    "devtools",
] }
tauri-plugin-log = "^2"
tauri-plugin-fs = "^2"
xcap = { git = "https://github.com/mg-chao/xcap", branch = "master" }
device_query = "^3"
log = "^0.4"
image = { version = "^0.25", features = ["png", "webp"] }
windows = { version = "0.61.1", features = [
    "Win32_Foundation",
    "UI_UIAutomation",
] }
thiserror = "2.0.12"
uiautomation = "^0.18"
rtree_rs = "^0.1.4"
atree = "^0.5.2"
tauri-plugin-dialog = "^2"
paddle-ocr-rs = "0.3.4"
# paddle-ocr-rs = { git = "https://github.com/mg-chao/paddle-ocr-rs.git", branch = "20250515_auto_rollback_angle" }
num_cpus = "^1.16.0"
tauri-plugin-http = "2"
get-selected-text = "0.1.6"
tauri-plugin-store = "2"
base64 = "0.22.1"
enigo = "0.3.0"
hora = { version = "0.1.1" }
imageproc = "0.25.0"
rayon = "1.10.0"
fast_image_resize = { version = "5.1.4", features = ["rayon"] }
bytemuck = "1.23.0"
tauri-plugin-clipboard-manager = "2"
clipboard-rs = "0.2.4"
tauri-plugin-opener = "2"
zune-jpegxl = "0.4.0"
zune-core = "0.4.12"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "^2"
