[profile.release.target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static,target-cpu=native"]

[profile.release.target.aarch64-apple-darwin]
rustflags = ["-Ctarget-feature=+crt-static,target-cpu=native"]

[env]
ORT_LIB_LOCATION = "./lib"
